### ISSUE TITLE
建议使用pm2实现进程守护

### ISSUE THREAD

**Issue by HPUhushicheng** [EternalmBlue/YunBanKe-AutoSign#2]
可以修改Main.kt,使用硬编码，
```sh
    UserLoginInfo.userName = "xxxx"
    UserLoginInfo.passWord = "xxxx"
```
配合pm2
```sh
pm2 start -n demo java -- -jar autosign-1.3.jar 
```
这里非常感谢作者的开源奉献，我原先也是做了云班课抓包分析的工作，但是由于技术不够，无法实现X-signature的参数，希望下次可以和作者交流思路

**Comment by EternalmBlue** [comment]
硬编码已经更新了，在jar文件同目录下会有个.txt用来输入账号密码，如果没输入，进入程序也会要求输入。如果在Main.kt 使用硬编码，可能有其他人并不会看源码，也就不会打开Main.kt这个文件。在同目录下生成一个txt文件应该可以最大可能照顾所有人。
pm2我没用过...而且windows环境下好像并没有默认安装，为了易用性就不更新pm2内容了。

**Comment by EternalmBlue** [comment]
进程守护的作用是什么?..如果不使用进程守护，程序进程会被自动kill吗。我在windows环境下挂在后台一下午没被kill过

**Comment by HPUhushicheng** [comment]
pm2是配合Ubuntu使用的，部署在服务器上手机shell即可操作开启与关闭，而且目前来看脚本已经失效，无法解决签到问题
